### ISSUE TITLE
3.30.20 release checklist

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#352]
It's not yet time for the 3.30.20 release (we are waiting on a final version of ADMB 13), but feel free to add notes about the release here

## Checklist for before prerelease
- [x] Update GHA to use ADMB 13 (IT)
- [x] SS testing and debugging completed (IT)
- [x] r4ss updated (IT)
- ~~Put together pre-release announcement (RM)~~
- ~~code committed and tagged in repo as v3.30.20-prerel, which will trigger a gha to build the prerelease executables (KJ)~~
- ~~All exes added to github releases as v3.30.20-prerel (KJ) (use exe artifacts from the gha in step above)~~
- ~~Announce prerelease (RM)~~

## Checklist for before release
- [x] Manual updated and tagged in repo (CW) - address at least issues with the [3.30.20 release label](https://github.com/nmfs-stock-synthesis/doc/issues?q=is%3Aissue+is%3Aopen+label%3A%223.30.20+release%22)
- [x] Manual added to a github release, include attaching a pdf version (KJ and CW)
- [x] Manual release version on website updated once pdf and html built (KJ) (update https://github.com/nmfs-stock-synthesis/doc/blob/main/docs/SS330_User_Manual_release.html to the 3.30.20 version; update links to link to 3.30.20 in https://github.com/nmfs-stock-synthesis/doc/blob/main/docs/index.md#links-to-documentation)
- [x] SSI updated and github release created (NS)
- [x] Make changes to SS3 if any bugs caught in prerelease (RM)
- [x] Check that ADMB version listed in files is correct (RM)
- [x] Change log updated in Stock Synthesis repo (RM)
- [x] Code committed and tagged in repo as v3.30.20, which will trigger a gha to build the release executables (KJ) (Instructions on [how to push a a local tag to a remote](https://github.com/nmfs-stock-synthesis/stock-synthesis/wiki/Stock-Synthesis:-practices-for-maintainers#how-to-push-a-local-tag-up-to-github))
- [x] Exe and .tpl archived on [Google drive](https://drive.google.com/drive/folders/1Gh_dXi8v3rqawpwn2N6yaaEXZPq6G2io) (KJ)
- [x] All exes added to github releases as v3.30.20 (KJ) (get exes in the artifacts of the gha that built the release exes)
- [x] Send out release announcement msg (RM)

## Checklist for after release
- [ ] examples updated in user-examples repo using [this script](https://github.com/nmfs-stock-synthesis/user-examples/blob/main/R/update_examples.R) (KJ)
- [ ] Update test-models reference files to the release version using [this update script](https://github.com/nmfs-stock-synthesis/test-models/blob/main/.github/r_scripts/update_ref_files.R) (KJ). also tag after updating with release number.
- [x] Removed "resolved" tag and close all issues worked in the milestone for this release (RM)
- [x] Move unworked issues for the release milestone to the next milestone (RM)

**Comment by k-doering-NOAA** [comment]
@kellijohnson-NOAA has kindly agreed to coordinate this release, so she will be making sure the checklist gets completed when the time comes for the release.

**Comment by k-doering-NOAA** [comment]
Note I reassigned tasks that I usually do to coordinate a release (by changing initials in the checklist), so please take a look and let me know if you have any concerns about any new tasks! I will be available to answer questions if they arise.

**Comment by Rick-Methot-NOAA** [comment]
The change log was still a blank slate for 3.30.20.  So rather than create al those entries, I am trying to just improve the labelling and linking for all the PRs and Issues in Milestone 3.30.20.  Is a milestone view publicly accessible?

**Comment by kellijohnson-NOAA** [comment]
If you navigate to [issues](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues) you can enter 
```
milestone:3.30.20 
```
in the search bar and it will search for issues and pull requests with that milestone.

**Comment by iantaylor-NOAA** [comment]
This is an area where Kathryn was the key to making the changelog happen.

Kelli's search could be linked in a release message but the list is pretty messy: https://github.com/nmfs-stock-synthesis/stock-synthesis/issues?q=milestone%3A3.30.20+ 

I was just looking at github projects and see that they are private by default. For instance, this milestone tracker is not visible when I'm not logged into github https://github.com/orgs/nmfs-stock-synthesis/projects/2/views/1, but it could easily be made public. It's a cleaner list for folks to look at, but still not great.

If you want a change log like what we've done in the past, I can budget some time tomorrow or next week to try to populate one.

**Comment by Rick-Methot-NOAA** [comment]
Thanks for feedback.  I know how to do it myself, what I am looking for is something that any user could easily do.

**Comment by k-doering-NOAA** [comment]
I thought about this a bit in the past and couldn't come up with a good, concise way to use the project board. What I had hoped to do (and didn't have time for) was to create a ghaction that pulled info from the Pull request form and populated the change log for us. Unfortunately, I think it is hard to automate a change log, because issues (and even pull requests) tend to be a bit messy.

At least with the PR template, I think someone could copy/paste the lines from it for this release, which is a little less work than in the past.

**Comment by Rick-Methot-NOAA** [comment]
I find this view from current Excel change log:
![image](https://user-images.githubusercontent.com/6250016/190759967-d1da64e5-9e66-4c9c-8c93-194be5d07e07.png)

no better than this view from modified project board:
![image](https://user-images.githubusercontent.com/6250016/190765345-bc7d5c8d-cddf-492e-aeca-7601859c4017.png)

The problem is sharing that view with the community.  It is a convenient format for reviewing what has been done; I can even edit labels from within that view.

**Comment by iantaylor-NOAA** [comment]
Good point Rick
To that end, I just created a new project called "change log", added all issues matching the following:
label:"change log" milestone:"3.30.19" status:"Done"
and changed the settings to make it public.
Here's the link https://github.com/orgs/nmfs-stock-synthesis/projects/11/views/1 which I think we could put into the release notes. Would that work?

Initially I created a "public change log" view within the "milestone tracker" project (it's still there), but realized that it would require making all the views in that project public if we want to make one of them public. I'm not sure that's a bad thing, but it could create more confusion than a single-view project like the one linked above.

**Comment by Rick-Methot-NOAA** [comment]
Thanks Ian.  I had created a change log view within the ss3-issue-tracker project, but if we are to share this it makes sense to have a dedicated project just for that purpose.

But we do not want too many projects because items need to be individually added to each project, so that favors putting things into just one project from which we can share views.

The project system in github favors putting Issues into the project and then letting the system display linked PR.  I like that.  So, I should stop putting PR directly into the project because it clutters things by having something represented by both a PR and an Issue, and not even adjacent rows.

**Comment by iantaylor-NOAA** [comment]
I think we could train ourselves to apply the "change log" label and add to the "change log" project at the same time on an issue worth including. Or we could do away with the "change log" label and just use the project board. Presumably those issues would already have been added to the "ss3-issue-tracker" project at the point that they started getting tracked or worked on.

I added the 3.30.20 milestone issues to the change log project and removed one pull request that were in that project. But that PR (https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/270) maybe should belong anyway because it includes a partial fix for one issue (#265) and the PR isn't showing up as linked to either #265 or #268 (which is now in the project).

I don't know how you created the milestone groupings in the ss3-issue-tracker.

**Comment by Rick-Methot-NOAA** [comment]
I just rearranged the columns so you can see each entries milestone level.  It is easy to click that entry pulldown to change it to a different milestone assignment.  Similarly, easy to add/delete labels.

**Comment by iantaylor-NOAA** [comment]
Thanks for the tip on the grouping option. I'm now sold on using a project board to replace the change log.
Yes, this can be a work in progress and we can get feedback from users and refine as we go. I'm not sure how many of them actually read the change log anyway.

**Comment by k-doering-NOAA** [comment]
Yes, great work, Rick! It's looking good.

**Comment by Rick-Methot-NOAA** [comment]
@kellijohnson-NOAA 
@iantaylor-NOAA 
@nschindler-noaa 
What is status of work to get ready for this release?   I would like to get it out on Friday this week.

**Comment by kellijohnson-NOAA** [comment]
@Rick-Methot-NOAA given that we are not doing a prerelease can I cross off the last four items in the pre-release checklist?

**Comment by Rick-Methot-NOAA** [comment]
go for it.

**Comment by kellijohnson-NOAA** [comment]
The repo has been tagged with v.3.30.20 and the executables can be found in [this zip file](https://github.com/nmfs-stock-synthesis/stock-synthesis/suites/8538188733/artifacts/381002592). The files can also be found on the [google drive here](https://drive.google.com/drive/folders/1FrbYmj_pHedOtEjdn1n8DE4FxKJIhb0b?usp=sharing). I tested the windows executable with {ss3sim} and everything appears to be fine. @Rick-Methot-NOAA do you want me to "Draft a new release", which is a [button available here](https://github.com/nmfs-stock-synthesis/stock-synthesis/releases) and add the exes or do you want to do that?

**Comment by Rick-Methot-NOAA** [comment]
You're on a roll.  Please do draft that new release and link to the [release message](https://docs.google.com/document/d/1zE6pWLNlRRqHe6-8JQDk67-s6_H4t3h1GuRcO7oL-1M/edit?usp=sharing) that I will broadcast  via VLAB

**Comment by Rick-Methot-NOAA** [comment]
Thank you Kelli and everyone contributing to this release
