### ISSUE TITLE
[Feature]: test and update to ADMB 13.1

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nmfs-stock-synthesis/stock-synthesis#392]
### Describe the solution you would like.

A minor release ADMB 13.1 was released today: https://github.com/admb-project/admb/releases/tag/admb-13.1

Here's a checklist copied from https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/257#issuecomment-1124950348 and modified based on a conversation between @iantaylor-NOAA and @k-doering-NOAA.

Perhaps @e-gugliotti-NOAA and I (@iantaylor-NOAA) can work on these together.

- [x] Install ADMB 13.1 on local computers for anyone interested in compiling SS3 locally
  - [ ] @Rick-Methot-NOAA 
  - [x] @iantaylor-NOAA 
  - [x] @e-gugliotti-NOAA 
- [x] Create branch of "workflows" repository that installs ADMB 13.1 instead of 13.0
- [x] Create branch of "stock-synthesis" that uses the workflows branch created above
- [x] Confirm that SS3 is compiling on all platforms (by checking for artifact of the [call-build-ss3](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/workflows/call-build-ss3.yml) github action)
  - [x] Linux
  - [x] Mac
  - [x] Win 
- [x] Can run models with no indication of memory leaks (look for "NA" values in the output and check the github action log file from model run for an error message that has something to do with "core dump", "SEGFAULT", or "malloc")
- [x] Model results are the same (should be tested by [call-run-ss3-with-est](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/workflows/call-run-ss3-with-est.yml) github action
- [ ] Model run times are similar or better (not sure if @k-doering-NOAA has an easy way to get the results reported here for ADMB 13.0: https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/257#issuecomment-1125039928 - comment by KD: what I usually do is extract the results from the log of a recent gha run that used ideally the same version of ss3. I download the log and extract the run times by searching the text file)
- [x] Check compiler warnings (should be checked by [call-build-ss3-warnings](https://github.com/nmfs-stock-synthesis/stock-synthesis/actions/workflows/call-build-ss3-warnings.yml) github action)
- [x] Formally convert over to ADMB 13.1
  - [x] merge branches for "workflows" and "stock-synthesis" repositories
  - [x] change admb version in SS3 headers (see https://github.com/nmfs-stock-synthesis/stock-synthesis/pull/374/files for previous change)

### Describe alternatives you have considered

Continue with ADMB 13.0
