### ISSUE TITLE
Release v3.30.21 checklist

### ISSUE THREAD

**Issue by e-gugliotti-NOAA** [nmfs-stock-synthesis/stock-synthesis#394]
# Release checklist

Created this release checklist in preparation for the v3.30.21 release _currently_ scheduled for mid-January. Please feel free to make changes to this checklist as you see fit.

## Checklist for before prerelease
- [ ] SS testing and debugging completed (RM and IT)
- [ ] r4ss updated (IT)
- [ ] Put together pre-release announcement (RM)
- [ ] code committed and tagged in repo as `v3.30.21-prerel` (RM)
- [ ] All exes added to github releases as `v3.30.21-prerel` (RM)
- [ ] Announce prerelease (RM)

## Checklist for before release
- [ ] Manual updated and tagged in repo (CW) - address at least issues with the [`v3.30.21` release milestone](https://github.com/nmfs-stock-synthesis/stock-synthesis/issues?q=is%3Aissue+is%3Aopen+milestone%3A3.30.21)
- [ ] Manual added to a github release, include attaching a pdf version (EG and CW)
- [ ] Manual release version on website updated once pdf and html built (EG) (update https://github.com/nmfs-stock-synthesis/doc/blob/main/docs/SS330_User_Manual_release.html to the `v3.30.21` version; update links to link to `v3.30.21` in https://github.com/nmfs-stock-synthesis/doc/blob/main/docs/index.md#links-to-documentation)
- [ ] SSI updated (NS)
- [ ] Make changes to SS3 if any bugs caught in prerelease (RM)
- [ ] Change log updated in Stock Synthesis repo (RM)
- [ ] Code committed and tagged in repo as `v3.30.21`, which will trigger a gha to build the release executables (EG) (Instructions on [how to push a a local tag to a remote](https://github.com/nmfs-stock-synthesis/stock-synthesis/wiki/Stock-Synthesis:-practices-for-maintainers#how-to-push-a-local-tag-up-to-github))
- [ ] Exe and .tpl archived on [Google drive](https://drive.google.com/drive/folders/1Gh_dXi8v3rqawpwn2N6yaaEXZPq6G2io) (EG)
- [ ] All exes added to github releases as `v3.30.21` (EG) (get exes in the artifacts of the gha that built the release exes)
- [ ] Send out release announcement msg (RM)

## Checklist for after release
- [ ] Examples updated in user-examples repo using [this script](https://github.com/nmfs-stock-synthesis/user-examples/blob/main/R/update_examples.R) (EG)
- [ ] Update ss-test-models reference files to the release version using [this update script](https://github.com/nmfs-stock-synthesis/test-models/blob/main/.github/r_scripts/update_ref_files.R) (EG). Also tag after updating with release number.
- [ ] Removed "resolved" tag and close all issues worked in the milestone for this release (RM)
- [ ] Move unworked issues for the release milestone to the next milestone (RM)
