### ISSUE TITLE
Release v3.30.22 checklist

### ISSUE THREAD

**Issue by e-gugliotti-NOAA** [nmfs-stock-synthesis/stock-synthesis#510]
# Release checklist

## Checklist for before release [stock synthesis repos will likely be awry for 1-2 days as all updates to repo names and release are updated]
- [x] Manual updated and tagged in repo (EG) - address at least issues with the [`v3.30.22` release label](add correct link to GitHub issues using filter: is:issue is:open label:"3.30.22 release" when available)
- [x] Manual added to a GitHub release, include attaching a pdf version (EG)
- [x] Manual release version on website updated once pdf and html built (EG) (update https://github.com/nmfs-stock-synthesis/doc/blob/main/docs/SS330_User_Manual_release.html to the `v3.30.22` version; update links to link to `v3.30.22` in https://github.com/nmfs-stock-synthesis/doc/blob/main/docs/index.md#links-to-documentation)
- [x] Make changes to SS3 if any bugs caught in prerelease (RM)
- [x] [Change log project board](https://github.com/orgs/nmfs-stock-synthesis/projects/11) updated with any issues labelled "change log" (RM)
- [x] Code committed and tagged in repo as `v3.30.22`, which will trigger a GHA to build the release executables (EG) (Instructions on [how to push a a local tag to a remote](https://github.com/nmfs-stock-synthesis/stock-synthesis/wiki/Stock-Synthesis:-practices-for-maintainers#how-to-push-a-local-tag-up-to-github))
- [x] Exe and .tpl archived on [Google drive](https://drive.google.com/drive/folders/1Gh_dXi8v3rqawpwn2N6yaaEXZPq6G2io) (EG)
- [x] All exes added to GitHub releases as `v3.30.22` (EG) (get exes in the artifacts of the GHA that built the release exes)
- [x] Send out release announcement msg (RM)
- [x] Add to release discussion on GitHub repository (EG)

## Checklist for after release
- [x] Update user-example models using [this GitHub action](https://github.com/nmfs-stock-synthesis/user-examples/blob/main/R/update_examples.R) and tag with new release number after updating (EG)
- [x] Update test models using [this GitHub action](https://github.com/nmfs-stock-synthesis/test-models/actions/workflows/update-ss3-models.yml) and tag with new release number after updating (EG)
- [x] Removed "resolved" tag and close all issues worked in the milestone for this release (RM)
- [x] Move unworked issues for the release milestone to the next milestone (RM)
- [x] Bring over the quarto website from @e-gugliotti-NOAA's personal repo to the nmfs-stock-synthesis org and update github.io sites with that one as well as remove the doc github.io index file.

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA are those last unchecked boxes good to go?

**Comment by Rick-Methot-NOAA** [comment]
Away from computer.  Will check tomorrow
