### ISSUE TITLE
Release v3.30.22.1 checklist

### ISSUE THREAD

**Issue by e-perl-NOAA** [nmfs-stock-synthesis/stock-synthesis#549]
# Release checklist

## Checklist to get ready for release
- [x] SS3 testing and debugging completed (RM and IT)
- [x] Check artifact from the `call-build-ss3-warnings` GitHub action for useful warnings (RM and IT)
- [x] r4ss updated (IT)
- [x] Make sure all issues relevant to the release are marked with v3.30.22.1 milestone **AND** have `change log` label (RM/EG)

## Checklist for before release
- [x] [Change log project board](https://github.com/orgs/nmfs-ost/projects/11) updated with any issues labelled "change log" (RM)
- [x] Manual updated in repo (EG) - address at least issues with the [`v3.30.22.1` release label](https://github.com/nmfs-ost/ss3-source-code/issues?q=is%3Aissue+milestone%3A3.30.22.1).
- [x] Manual release date and version changed in .tex file, tagged and added to a GitHub release, include attaching a pdf version (EG). (Instructions on [how to push a a local tag to a remote](https://github.com/nmfs-ost/ss3-source-code/wiki/Stock-Synthesis:-practices-for-maintainers#how-to-push-a-local-tag-up-to-github)).
- [x] Manual release version on website updated once pdf and html built (EG) (update https://github.com/nmfs-ost/ss3-doc/blob/main/docs/SS330_User_Manual_release.html to the `v3.30.22.1` version. Don't forget to change the version for the pdf link in the docs/index.md.
- [x] Code committed and tagged in repo as `v3.30.22.1`, which will trigger a GHA to build the release executables (EG) (Instructions on [how to push a a local tag to a remote](https://github.com/nmfs-ost/ss3-source-code/wiki/Stock-Synthesis:-practices-for-maintainers#how-to-push-a-local-tag-up-to-github))
- [x] Exe and .tpl archived on [Google drive](https://drive.google.com/drive/folders/1Gh_dXi8v3rqawpwn2N6yaaEXZPq6G2io) (EG)
- [x] All exes added to GitHub releases as `v3.30.22.1` (EG) (get exes in the artifacts of the GHA that built the release exes)
- [x] Send out release announcement msg (RM)
- [x] Add to release discussion on GitHub repository (EG)

## Checklist for after release
- [x] Update user-example models using [this github action](https://github.com/nmfs-ost/ss3-user-examples/blob/main/R/update_examples.R) and tag with new release number after updating (EG)
- [x] Update test models using [this github action](https://github.com/nmfs-ost/ss3-test-models/actions/workflows/update-ss3-models.yml) and tag with new release number after updating (EG)
- [x] Removed "resolved" tag and close all issues worked in the milestone for this release (RM)
- [x] Move unworked issues for the release milestone to the next milestone (RM)

**Comment by e-perl-NOAA** [comment]
Agreed. It would be a rush to get out today with all of the meetings that I have this afternoon.
