### ISSUE TITLE
[Feature]: Equilibrium growth for equilibrium calculations

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#58]
Imported from redmine, Issue [#70928](https://vlab.ncep.noaa.gov/redmine/issues/70928)
 Opened by @RickMethot on 2019-11-05
Status when imported: Under Review
 
benchmark calculations should be able to recalculate growth from averaged parameters rather than calculating average length from the range of years.

per Andre Punt comment at CAPAM

Code development logic below:

----------------
To achieve density-dependence, need to put biology calcs in a loop.
First stage code development steps:
  create averaged MG parms
   create biology-at-age from those parameters and store in styr-1 if in time_series, or styr-3 for benchmark

Second stage
   put equil calcs in a loop
   do the first stage calcs
   loop 1 is with F=0; store store resultant equil quantities (SSB and SmryBio, etc. ) for use in density-dependent calcs
   loop 2 with specified F; store resultant equil quantities; update biology-at-age
   loop 3+: adjust Density-dependent parameters, including spawner-recruitment; update resultant equil quants; update biology-at-age; repeat
  The calculations without density-dependence are easier because it only involves the first stage calcs.
  Also, to gain some speed, the 3*Amax extra ages in equil_calcs might be made conditional such that it only occurs in the last iteration.
  For styr-1, this could be invoked using this existing option:
    0/1 to use steepness in initial equ recruitment calculation

**Comment by Rick-Methot-NOAA** [comment]
in addition to equilibrium, it would be extraordinarily informative if density-dependent parameters could also be active in the benchmark calculations.  Note that density-dependent parameters **are** be active in forecast in existing code.
@puntae

**Comment by Rick-Methot-NOAA** [comment]
Steps in the calculation:

1. get parameters to use for the calculations; could involve averaging over a range of years
2. set y=styr-2, which currently is unused row of matrices
3. determine how many iterations are needed.  Only 1 in simple case, several for area-specific S-R or for D-D parameters
4. in each iteration, do same calculations as get_initial_conditions() except when there are multiple iterations, the parameter values used in an iteration need to be adjusted according to results of the previous iteration.  Also, to gain some speed, the 3*Amax extra ages in equil_calcs might be made conditional such that it only occurs in the last iteration.

**Comment by Rick-Methot-NOAA** [comment]
First stage code development steps:
- [ ] create averaged MG parms
- [ ] create biology-at-age from those parameters and store in styr-2
Second stage
- [ ] put equil calcs in a loop
- [ ] do the first stage calcs
- [ ] loop 1 is with F=0; store store resultant equil quantities (SSB and SmryBio, etc. ) for use in density-dependent calcs
- [ ] loop 2 with specified F; store resultant equil quantities; update biology-at-age
- [ ] loop 3+:  adjust Density-dependent parameters, including spawner-recruitment; update resultant equil quants; update biology-at-age; repeat
