### ISSUE TITLE
Make Dirichlet-Multinomial likelihood available for generalized size frequency data

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#66]
Imported from redmine, Issue [#74989](https://vlab.ncep.noaa.gov/redmine/issues/74989)
 Opened by @iantaylor-NOAA on 2020-02-14
Status when imported: New
 
This task was pulled out of issue #28432 as it may take longer than the other pieces of that issue and thus may not get done for 3.30.15

**Comment by k-doering-NOAA** [comment]
Tasks for this issue:
- [ ] Make DM likelihood available for generalized size frequency data
- [ ] Included DM likelihood in bootstrapping for generalized size frequency data (from #52)

**Comment by Rick-Methot-NOAA** [comment]
Thanks Nancie.  I agree and also for some of the tuna assessments.

**Comment by k-doering-NOAA** [comment]
@Rick-Methot-NOAA, do you think this should be added to 3.30.20, then? Or is it fine as-is on milestone 3.30.21

**Comment by Rick-Methot-NOAA** [comment]
current input for gen_size is formatted very differently from the input for length or age comp.  It is by method, not by fleet because a fleet could use multiple methods.
1 # N sizefreq methods to read 
 25 #Sizefreq N bins per method
 2 #Sizetfreq units(1=bio/2=num) per method
 3 #Sizefreq scale(1=kg/2=lbs/3=cm/4=inches) per method
 1e-09 #Sizefreq:  add small constant to comps, per method 
 80 #Sizefreq N obs per method

Proposal:
- [ ] use -1 as the N methods to invoke new approach
- [ ] rotate input from column to row orientation to be more like length and age comp
- [ ] read the rows in pushback mode like other inputs
- [ ] provide placeholders in those rows for all features currently in lencomp, even if not yet implemented here
- [ ] implement the D-M likelihood
