### ISSUE TITLE
add option for forecast to use averaged M or other biology parms

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/stock-synthesis#68]
Trying a new prototype template here.  This section will continually be edited as development progress.
- [ ] Issue description
For various MGparms, notably M and recruitment distribution, there is a need to be able to calculate the average over some range of years during which the factor is time-varying, and to assign that average to each year of the forecast.

- [ ] summary of major aspects of code revision

- fcast_loop_control(5) is unused and will be re-purposed to invoke the needed inputs
-  add new list based input of MG_type, start year, end year
-    terminate with MG_type = -9999
-    for MG_type, use this scheme:  1=natural_mortality  (M), 2=growth, 3=wtlen, 4=recr_dist&femfrac, 5=migration, 6=ageerror, 7=catchmult, 8=hermaphroditism, 9=maturity&fecundity

- [ ] example input change, with zip
This new approach has input with 4 values that looks like this.
```
1 #_Fcast_MGparm_averaging: 0 = not, 1 = do
#_read list of MG_type, method (1, 2), start year, end year
#_Terminate with -9999 for MG_type
#_MG_type: 1=M, 2=growth, 3=wtlen, 4=recr_dist&femfrac, 5=migration, 6=ageerror, 7=catchmult, 8=hermaphroditism
#_Method = 0 (default) means continue time_vary parms; 1 means to use average of derived biology; 2 (future) means average parameter then apply as if time-vary
#_MG_type method st_year end_year 
1 1 2002 2003 # (M) NatMort 
4 1 2016 2018 # RecrDist 
-9999 -1 -1 -1

```
- [ ] example output change
- [ ] draft text for manual

----------------------------------------------------------------
History and commentary below
Imported from redmine, Issue [#75321](https://vlab.ncep.noaa.gov/redmine/issues/75321)
 Opened by @RickMethot on 2020-02-24
Status when imported: New
 
While working with Steve Barbeaux, we found a need to manually create a block for forecast years so that a M value calculated for benchmark years could be hardwired in as the forecast M.

The current forecast input does not allow for specifying biology:
#_Fcast_years:  beg_selex, end_selex, beg_relF, end_relF, beg_mean recruits, end_recruits  (enter actual year, or values of 0 or -integer to be rel. endyr)
 2018 2018 2014 2018 1977 2019

**Comment by Rick-Methot-NOAA** [comment]
This could be done using this unused option:
0 #_Forecast loop control #5 (reserved for future bells&whistles) 
If this value is = 1 then read range of years for averaging the parameters for each of:
1=M, 2=fecundity, 3=recruit_dist, 4=herma, 5=len-wt, 6=frac_female
do input as a list and terminate with -9999
example:
1  2002  2022  #  input for doing M
4 2004  -1 # input for herma  
# where -1 for ending year means to use endyr; -2 could mean to use same as benchmark_yr, but make these codes logical relative to other codings
-9999 0 0   # terminator 
By doing this as a list, we do not need to implement all the options at same time.

The parameter averaging would happen near top of benchfore code.  The parameter getting averaged would get flagged as having a block and the value assigned to the block would be that average.

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa  Neal, this issue is another candidate for you to work on this spring.

**Comment by akatan999** [comment]
Full control of the biology both in benchmark and in forecast would really be a great addition especially with the increasing use of time varying parameters as for example M from MSVPA or weight and fecundity in models that uses weight at age file.

**Comment by Rick-Methot-NOAA** [comment]
What I am proposing will work well for growth based models and for M in empirical wt-at-age models.  But it will not address forecast wt-at-age for empirical wt-at-age models.  For that, it is up to the user to do the averaging themselves and enter it into the wtatage.ss file.

**Comment by akatan999** [comment]
Correct, which is what we do now for those models, we input the wtatage we want directly in the wtatage.ss file.

**Comment by Rick-Methot-NOAA** [comment]
Note that for the averaging of biology for benchmark, it is done for all types of biology using the same year range.  Note that the averaging for recr_dist is done differently because recr_dist previously was not stored annually.  Now it is, so could be changed to be same as M, etc.  Also, note that for benchmark biology, hermaphroditism and sex_ratio are not included in average.  But let us not deal with benchmark now; instead do that when work occurs on issue #58 for equilibrium growth

**Comment by Rick-Methot-NOAA** [comment]
@nschindler-noaa 
for biology averaging for forecast, you can take code logic like that found in ss_benchfore at line 311 and adapt it to the new code you already added to forecast section.  The only difference is that the averaged result will get stored in each year of the forecast (endyr+1 to Yrmax), rather than in styr-3.  Let's do that for migrrate and recr_dist to get started.
